/* eslint-disable import/prefer-default-export */

export const typeDict = {
  TEXT: '文本',
  URL: 'URL',
  EMAIL: '邮箱',
  PHONE: '电话',
  TEXT_AREA: '多行文本框',
  NUMBER: '数字',
  CURRENCY: '金额',
  PERCENT: '百分比',
  CAL_FORMULA: '计算字段',
  COLLECTION: '汇总归集',
  SEARCH_CONDITION: '搜索条件',
  RANGE_CONDITION: '筛选范围',
  DATE: '日期',
  FILE: '文件',
  SELECT: '单选',
  CASCADER: '级联',
  SELECT_MULTIPLE: '多选',
  KV_TREE: '键值对树',
  SELECT_MULTIPLE_REMOTE: '远程多选',
  SELECT_REMOTE: '远程单选',
  CASCADE: '级联单选',
  SELECT_SEARCH: '可搜索单选',
  SINGLE_CHECKBOX: '复选框',
  TRANSFER: '穿梭框',
  REF_FIELD: '引用字段',
  RELATION_MULTIPLE: '多选查找',
  RELATION_MULTIPLE_SUMMARY: '多选查找关联字段',
  RELATION_SINGLE: '单选查找',
  RELATION_SINGLE_SUMMARY: '单选查找关联字段',
};
